# @package _global_
# XGBoost with strong regularization - reduces overfitting

model:
  name: CatBoost
  params:
    n_estimators: 100
    max_depth: 5
    learning_rate: 0.1
    min_child_weight: 3
    subsample: 0.7
    colsample_bytree: 0.7
    reg_alpha: 0.1
    reg_lambda: 1.0
    gamma: 0.2
    random_state: 42
    eval_metric: logloss
