# @package _global_
# XGBoost with deeper trees - better for complex patterns

model:
  name: CatBoost
  params:
    n_estimators: 150
    max_depth: 10
    learning_rate: 0.03
    min_child_weight: 1
    subsample: 0.9
    colsample_bytree: 0.9
    gamma: 0.1
    random_state: 42
    eval_metric: logloss
