# @package _global_
# GradientBoostingClassifier with deeper trees

model:
  name: GradientBoosting
  params:
    n_estimators: 150
    max_depth: 5
    learning_rate: 0.03
    min_samples_split: 2
    min_samples_leaf: 1
    subsample: 0.9
    random_state: 42
