# @package _global_
# LightGBM with shallow trees - better for interpretability

model:
  name: LightGBM
  params:
    n_estimators: 200
    max_depth: 3
    learning_rate: 0.05
    num_leaves: 15
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    verbose: -1
