# @package _global_
# Small Transformer configuration - lightweight for small datasets

model:
  name: Transformer
  params:
    d_model: 128
    nhead: 4
    num_layers: 2
    dim_feedforward: 256
    dropout: 0.4
    weight_decay: 5e-4
    
    mixup:
      enabled: false
      alpha: 0.0
    
    gaussian_noise:
      enabled: true
      std: 0.01
    
    label_smoothing: 0.02
    
    optimizer:
      name: AdamW
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 1e-8
    
    scheduler:
      name: cosine
      warmup_proportion: 0.08
      min_lr: 0.0
    
    swa:
      enabled: true
      final_epochs: 30
    
    training:
      batch_size: 128
      epochs: 300
      early_stopping:
        enabled: true
        monitor: val_loss
        patience: 50
      auto_device: true
    
    random_seed: 42
