# @package _global_
# Default Transformer configuration - balanced for general use

model:
  name: Transformer
  params:
    d_model: 64
    nhead: 4
    num_layers: 2
    dim_feedforward: 128
    dropout: 0.3
    weight_decay: 1e-4
    
    mixup:
      enabled: false
      alpha: 0.0
    
    gaussian_noise:
      enabled: false
    
    label_smoothing: 0.0
    
    optimizer:
      name: Adam
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 1e-8
    
    scheduler:
      name: null
    
    swa:
      enabled: false
    
    training:
      batch_size: 128
      epochs: 100
      early_stopping:
        enabled: true
        monitor: val_loss
        patience: 10
      auto_device: true
    
    random_seed: 42
