# @package _global_
# XGBoost with shallow trees - better for interpretability

model:
  name: XGBoost
  params:
    n_estimators: 200
    max_depth: 3
    learning_rate: 0.05
    min_child_weight: 5
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    eval_metric: logloss
